version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.apache.spark:spark-sql_2.12
    versions:
    - 3.1.0
  - dependency-name: org.apache.spark:spark-catalyst_2.12
    versions:
    - 3.1.0
  - dependency-name: org.apache.spark:spark-hive_2.12
    versions:
    - 3.1.0
  - dependency-name: org.apache.spark:spark-avro_2.12
    versions:
    - 3.1.0
  - dependency-name: org.apache.spark:spark-core_2.12
    versions:
    - 3.1.0
  - dependency-name: org.llorllale:cactoos-matchers
    versions:
    - "0.23"
