language: java
sudo: false
addons:
  sonarcloud:
    organization: "andreoss"

cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=andreoss_etoile -Dsonar.login=e905a0238eb393aea61ea978baaefc1461786f87
jdk:
  - openjdk11
