
name: build

on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs:
  test:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test
        run: mvn clean test
